#!/usr/bin/env python3

import sys, json, shutil, subprocess, os, codecs

path = f"{os.path.dirname(os.path.abspath(sys.argv[0]))}/../config"

uname = shutil.which("uname")
nproc = shutil.which("nproc")

if uname == None:
	print("couldn't find utility uname!")
	sys.exit(1)

if nproc == None:
	print("couldn't find utility nproc!")
	sys.exit(1)

options = {}
options["arch"] = subprocess.check_output([uname, "-m"], stderr=subprocess.DEVNULL)
options["cpus"] = subprocess.check_output([nproc], stderr=subprocess.DEVNULL)
options["log_quiet"] = 1
options["skip_tool_check"] = 0

if os.path.isdir("/sys/firmware/efi"):
	options["arch_boot_platform"] = "uefi"

if os.path.isfile(path):
	print("config already exists!")
	sys.exit(1)

file = open(path, "a")
file.write(f"#Default config generated by {sys.argv[0]}\n\n")

for key, option in options.items():
	if type(option) is bytes:
		file.write(f"{key.upper()} = {option.decode('unicode_escape')}")
	elif type(option) is bool:
		file.write(f"{key.upper()} = {int(option == True)}")
	else:
		file.write(f"{key.upper()} = {option}\n")
